エンドポイントurl取得しcurl実行

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -53,14 +53,15 @@ jobs:
     - name: Install dependencies
       run: npm install
 
-    # API Gatewayエンドポイントのテスト
     - name: Test API Gateway endpoint using curl
       run: |
-        endpoint_url=$(cat endpoint.txt)
-        response=$(curl -X PUT $endpoint_url -H "Content-Type: application/json; charset=UTF-8" -d "{\"userId\":\"example@email.com\",\"mDt\":\"2021-12-31T23:59:59.999Z\",\"lat\":\"35.6895\",\"lng\":\"139.6917\",\"speed\":10,\"driveMode\":1,\"charge\":80,\"driveUnitErr\":\"00000000\",\"lockState\":true,\"lockId\":\"XXX0000\",\"lockErr\":\"00000000\"}")
-        
-        # 応答に期待するキーが含まれているかをチェックする
-        echo "$response"
-        echo "$response" | grep '"userId"'
-        echo "$response" | grep '"rDt"'
-
+         endpoint_url=$(cat endpoint.txt)
+         response=$(curl -X PUT $endpoint_url -H "Content-Type: application/json; charset=UTF-8" -d "{\"userId\":\"example@email.com\",\"mDt\":\"2021-12-31T23:59:59.999Z\",\"lat\":\"35.6895\",\"lng\":\"139.6917\",\"speed\":10,\"driveMode\":1,\"charge\":80,\"driveUnitErr\":\"00000000\",\"lockState\":true,\"lockId\":\"XXX0000\",\"lockErr\":\"00000000\"}")
+    
+      if [ $? -ne 0 ]; then
+        echo "curl command failed!"
+        exit 1
+      else
+        echo "curl command succeeded!"
+        echo "Response: $response"
+      fi
